[
    ./security/sftpjail
    ./security/sgx
    ./security/vault
    ./services/cluster/kubernetes/calico
    ./services/hardware/hp-ams
    ./services/misc/drone
    ./services/networking/calico
    ./services/networking/eidolon
    ./services/security/vault
    ./services/web-apps/mediawiki
]
