[
  ./security/sftpjail
  ./services/cluster/kubernetes/calico
  ./services/misc/drone
  ./services/networking/calico
  ./services/networking/eidolon
  ./services/security/hsm/ncipher
  ./services/security/vault-ssh-helper
  ./services/web-apps/mediawiki
]
